microsoft/Azure-Kinect-Sensor-SDK

CMakeLists.txt
azure-pipelines.yml
src/sdk/CMakeLists.txt

- Changes all binaries to also search for local path for shared objects. This emulates the same behavior on Windows. The shared object search path on Linux is now (list taken from: https://amir.rachum.com/blog/2016/09/17/shared-libraries/#runtime-search-path)
1. Directories in the LD_LIBRARY_PATH environment variable, which contains colon-separated list of directories (e.g., /path/to/libdir:/another/path)
2. Directory of the executable or shared object doing the loading
3. The list of directories in the file /etc/ld.so.conf. This file can include other files, but it is basically a list of directories - one per line.
4. Default system libraries - usually /lib and /usr/lib (skipped if compiled with -z nodefaultlib).
This better lines up with the Windows DLL search path …

Linux binaries search local path for shared objects

---

extern/libusb/CMakeLists.txt

Fix error C2001 on multibyte character environment by add compile option to specify character set. 
- Add compiler option <code>/source-charset:utf-8</code> when build on Windows.
**(Sorry, I can't tests with device because Azure Kinect is not released in Japan.)**

Fix error C2001 on multibyte character environment

---

include/k4a/k4a.h
include/k4ainternal/color.h
src/color/color.cpp
src/color/color_priv.h
src/color/mfcamerareader.cpp
src/color/mfcamerareader.h
src/color/uvc_camerareader.cpp
src/color/uvc_camerareader.h
src/sdk/k4a.c
tests/ColorTests/FunctionalTest/color_ft.cpp

- Add k4a_device_get_color_control_capabilities() API to query color camera control capabilities
color functional test (color_ft) include testing this feature.

New API to query color camera control capabilities.

---

CMakeLists.txt

- Turns on the "--as-needed" flag for all gcc and clang builds

Turn on "--link-as-needed" linker flag

---

tests/ColorTests/FunctionalTest/CMakeLists.txt

- Add color_ft as a functional test for platforms (removed Windows only if)

Enabling color_ft to run on Linux

---

src/record/sdk/CMakeLists.txt
src/sdk/CMakeLists.txt
tests/UnitTests/dynlib_ut/CMakeLists.txt

- Changes SONAME to only include K4A_VERSION_MAJOR

Set SONAME to libk4a.so.MAJOR_VER

---

CMakeLists.txt
src/record/sdk/CMakeLists.txt
src/sdk/CMakeLists.txt
tools/k4arecorder/CMakeLists.txt
tools/k4aviewer/CMakeLists.txt
tools/updater/CMakeLists.txt

- Splits up our install files into multiple components
- This will allow for the creation of multiple debian packages
- Includes all our tools in the install path
For additional information. This create "components" as part of our install process. This will only matter for our debian package. Our zip and tar.gz packages will still be one large zip.

Install k4arecorder k4aviewer

---

src/record/sdk/CMakeLists.txt
src/sdk/CMakeLists.txt

- Replaces the use of NAMELINK_COMPONENT in install commands in CMakeLists.txt with NAMELINK_SKIP
- Fixes compatability with CMake 3.10

Remove use of NAMELINK_COMPONENT

---

include/k4a/k4a.h
include/k4a/k4a.hpp
include/k4ainternal/capturesync.h
include/k4ainternal/color_mcu.h
src/capturesync/capturesync.c
src/color_mcu/color_mcu.c
src/sdk/k4a.c

- k4a_device_start_cameras should use const k4a_device_configuration_t
- Azure Kinetic Viewer Sanity check

k4a_device_start_cameras should use const k4a_device_configuration_t

---

src/transformation/transformation.c

- Ensure xytable in transformation API is 16-byte aligned
Tested transformation example as well as the Azure Kinect viewer as well on both windows and linux

 Ensure xy_tables in transformation code is 16-byte aligned

---

azure-pipelines.yml

- Removes fetch depth on CI system
There was a change from git 2.21 to 2.22 that is causing our git checkout commands to fail in CI. While we determine what that change was and how to work around it, we should disable fetch depth as a quick fix.
First failed build is here: https://dev.azure.com/ms/Azure-Kinect-Sensor-SDK/_build/results?buildId=22610
Last successful build is here: https://dev.azure.com/ms/Azure-Kinect-Sensor-SDK/_build/results?buildId=22565
You can see the git verison on the Linux agent in the checkout step.

Do not limit fetch depth in CI

---

azure-pipelines.yml
src/record/sdk/CMakeLists.txt
src/sdk/CMakeLists.txt

- Our existing packaging wasn't providing the symlink to `libk4a.so`, so you couldn't easily link against it. This should allow linking with `-lk4a` again.

Fix symlink in debian package

---

azure-pipelines.yml

Update the develop branch build pipeline to use the candidate firmware 1.6.102075014.

Update develop to use the candidate firmware

---

docs/releasing.md

These files come in the development, not runtime, packages.

Corrected spec for the libk4a symlinks

---

include/k4a/k4a.h

- Improve the doc to explain how to get depth value in color camera space when using calibration function

Improve the sensor sdk calibration function usage

---

docs/depthengine.md

- Improves instructions for obtaining the depth engine on Linux

Add better details for obtaining the linux depth engine

---

include/k4a/k4atypes.h
src/color/color_priv.h

- Adding comments to code to document exposure mapping

Added code based comment to address exposure mapping

---

src/dynlib/CMakeLists.txt
src/dynlib/dynlib_windows.c

- Adding logic to add the current module path to the search path when attempting to load the depth engine.

Add the current module path to the search path

---

include/k4a/k4atypes.h

- Document details of how rotation matrix stored
- Document details of translation vector units

Document details of extrinsics

---

docs/building.md

Fix broken link in [docs/building.md#L131](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md#L131).
- Fix broken link in [docs/building.md#L131](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md#L131).  
It is difference between lower-case (k4a.sln) and upper-case (K4a.sln) in first character.  
It doesn't problem on local, but it can't follow links on GitHub (404 is displayed).

Fix broken link in docs/building.md

---

examples/playback_external_sync/main.c
examples/transformation/main.cpp
include/k4ainternal/matroska_read.h
include/k4arecord/playback.h
include/k4arecord/playback.hpp
include/k4arecord/types.h
src/record/internal/matroska_read.cpp
src/record/sdk/playback.cpp
src/record/sdk/record.cpp
tests/RecordTests/UnitTest/playback_perf.cpp
tests/RecordTests/UnitTest/playback_ut.cpp
tests/RecordTests/UnitTest/sample_recordings.cpp
tests/RecordTests/UnitTest/test_helpers.h
tools/k4aviewer/k4arecordingdockcontrol.cpp
tools/k4aviewer/k4arecordingdockcontrol.h

- Changes `get_next_capture()` / `get_previous_capture()` to return images with device timestamp instead of relative file timestamps.
- Deprecate `k4a_playback_get_last_timestamp_usec()` and replace with `k4a_playback_get_recording_length_usec()`
- Add `K4A_PLAYBACK_SEEK_DEVICE_TIME` for seeking to a device timestamp
I've split this off from #246 so it's easier to review, and included some of the test suite changes from the other PR.

Convert all playback timestamps to use device time

---

src/csharp/Examples/WPF/MainWindow.xaml.cs
src/csharp/SDK/Native/NativeMethods.cs
src/csharp/Tests/StubGenerator/NativeMethods.cs

- Corrected calling convention on callback delegates.

Fixed x86 calling conventions in C#

---

azure-pipelines.yml

- Removes the expectation of the connection exerciser being connected in the test lab

Removing Connection Exerciser from the test lab

---

include/k4a/k4a.hpp

- Adds a `capture::handle()` method to the C++ wrapper, allowing access to the underlying k4a_capture_t when using the C++ wrapper. This is needed to allow the C++ wrapper and the Body Tracking SDK to work together
Changes tested manually by compiling the Azure Kinect ROS Driver project with the changes, and accessing a k4a_capture_t handle using the new method.

Add a capture::handle() function to k4a.hpp

---

CMakeLists.txt
VersionInfo.cs.in
src/csharp/.gitignore
src/csharp/Examples/WPF/Properties/AssemblyInfo.cs
src/csharp/Examples/WinForms/Properties/AssemblyInfo.cs
src/csharp/Extensions/WPF/Properties/AssemblyInfo.cs
src/csharp/Extensions/WinForms/Properties/AssemblyInfo.cs
src/csharp/K4a.sln
src/csharp/SDK/Microsoft.Azure.Kinect.Sensor.csproj
src/csharp/Tests/FunctionalTests/Microsoft.Azure.Kinect.Sensor.FunctionalTests.csproj
src/csharp/Tests/FunctionalTests/Properties/AssemblyInfo.cs
src/csharp/Tests/StubGenerator.UnitTests/Microsoft.Azure.Kinect.Sensor.Test.StubGenerator.UnitTests.csproj
src/csharp/Tests/StubGenerator.UnitTests/Properties/AssemblyInfo.cs
src/csharp/Tests/StubGenerator/Microsoft.Azure.Kinect.Sensor.Test.StubGenerator.csproj
src/csharp/Tests/StubGenerator/Properties/AssemblyInfo.cs
src/csharp/Tests/UnitTests/Microsoft.Azure.Kinect.Sensor.UnitTests.csproj
src/csharp/Tests/UnitTests/Properties/AssemblyInfo.cs
src/csharp/VersionInfo.cs
src/csharp/k4a.props

- Switch .NET Standard and .NET Core projects to using AssemblyInfo and VersionInfo.
- Generate the VersionInfo file curing the CMake configure step.

Csharp version

---

docs/building.md

- Bolds instructions on using Visual Studio Developer Command Prompt
I used VSCode to manually view a rendering of the mark down to make sure the bold text appeared as expected

Bolds visual studio dev cmd prompt note

---

CMakeLists.txt
cmake/K4AProjectVersion.cmake

- Changes CMake project version from 1.1 to 1.2.
- Adds logic in the validate major and minor versions match between cmake and any version string.
- x ] I [built my changes](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md) locally

Updates cmake project version to 1.2

---

examples/undistort/main.cpp

- More clear naming of the enum
- add comments for a function

Small updates on comments and enum naming

---

src/record/sdk/CMakeLists.txt
src/sdk/CMakeLists.txt

- Sets `-fvisibility=hidden` for GCC and Clang compilation
- Sets `-Wl,--exclude-libs,ALL` for GCC and Clang linking
I tested this by comparing the output of `nm -D bin/libk4a.so` before and after this change. Before this change we were exporting functions from our internal libs and third party dependencies. After this change we only exported functions marked as K4A_EXPORT.

Sets default visibility of functions to hidden on Linux

---

CMakeLists.txt
azure-pipelines.yml
cmake/GitCommands.cmake
cmake/SourceLink.cmake

Turns on source linking for VS2019 builds
Source linking is a new way to index sources in PDBs. It embeded a JSON into the PDB which tells the debugger where to find the source files. Note, this only works in VS2019 because of file case issues in VS2017. Therefore issue #32 will not be resolved until we start shipping binaries from VS2019.
To manually test this, I built a PDB with these flags off the develop branch. Then I deleted all my sources and tried to debug a unit test in VS2019. VS2019 was able to download the sources from GitHub.
Note: Source linking does not appear to work in WinDBG. I have an internal ask out about that.

Enables SourceLink for Windows Builds

---

src/firmware/firmware.c

- Allows firmware_create to succeed if only the depth MCU is found

Reset now succeeds if Color camera is hung

---

include/k4a/k4a.hpp

This pull request will add default timeout argument to C++ wrapper (k4a/k4a.hpp).
In many use cases, timeout will specify <code>K4A_WAIT_INFINITE</code>.
Please read this proposal #632.
- Add default timeout argument

Add default timeout argument

---

tools/k4aviewer/linmath.h

Fix float literal.
- Fix float literal in mat4x4_from_quat function.

Fix float literal

---

include/k4a/k4a.h
include/k4a/k4a.hpp
include/k4ainternal/transformation.h
src/sdk/k4a.c
src/transformation/transformation.c
tests/Transformation/transformation.cpp

- API to transform pixel from color image to depth image without requiring transform the entire depth image to color camera for getting the corresponding depth, instead, we search on epipolar line to find the best candidate
- Unit test

Add API to transform pixel from color image to depth image with searching on epipolar line

---

examples/undistort/main.cpp

- Ignore interpolation at large depth discontinuity if user choose to use bilinear interpolation during undistort

Ignore interpolation at large depth discontinuity

---

examples/green_screen/MultiDeviceCapturer.h
examples/green_screen/main.cpp

- Added a timeout of 60s in the event the example can not sync images
- Added debug output to furthar debug the problem
- Removed all 'throw' and replaced with exit(1) (for error)
- Added return 0 to the end of main when the app runs to completion.

Green screen should timeout if it can not get sync'd images

---

examples/green_screen/main.cpp

Fix calibration to color camera matrix, and change matrix initialize method.
- Change matrix initialize method to cv::Mat33f::eye().  
It initialize matrix with identity matrix. It is suitable for this case.  
- Fix calibration to color camera matrix.  
camera_matrix( 1, 1 ) is fy.

Fix calibration to color camera matrix

---

include/k4a/k4a.hpp

- Adds a device::handle() method to the C++ wrapper, allowing access to the underlying k4a_device_t when using the C++ wrapper. This is needed to allow the C++ wrapper and the recording API to work together.
Specifically, <code>k4a_record_create()</code> requests a <code>k4a_device_t</code> handle in second argument.
```cpp
k4a_record_t recording_handle = nullptr;
k4a_record_create( path, device.handle(), device_configuration, &recording_handle );
```

Add a device::handle() function to k4a.hpp

---

src/csharp/Examples/WPF/MainWindow.xaml.cs
src/csharp/Examples/WinForms/Form1.cs

Reduced ColorResolution of the WPF and WinForms sample to R720p to get max 30fps performance instead of 10fps. The MainWindow's height is much less than 720p so the higher res color frames are just wasted computing.
-
-
-

Reduced WPF/WinForms sample ColorResolution to R720p for faster processing

---

CMakeLists.txt
extern/CMakeLists.txt
src/record/sdk/CMakeLists.txt
src/sdk/CMakeLists.txt
tests/UnitTests/dynlib_ut/CMakeLists.txt
tests/UnitTests/dynlib_ut/testdynlib.c

- Properly sets visibility flags for GCC / Clang
I used the following command before and after this change to verify we are not longer exporting `libjpeg` functions
`nm -gC bin/libk4a.so | grep jpeg_CreateDecompress`

Properly Sets default visibility of functions

---

tools/updater/main.c

- Adds `failed` to AzureKinectFirmwareTool on a failed reset
I was not able to repro this locally so I'm relying on the CI machines to verify this works.

Adds better logging to firmware tool on failure

---

azure-pipelines.yml

- Updates docker image for Linux build to come from the Microsoft Container Registry
This change (should) be essentially a no-op since the docker image we are building on is the same, just pulled from a different spot.

Updates docker build to pull from MCR

---

src/transformation/CMakeLists.txt

- Restricts `-msse4.1` flags to processors which (might) support it
I built this change under Linux and made sure the `-msse4.1` flag still existed.

Restrict MSSE flags to arch that support it

---

tests/FirmwareTests/firmware_helper.cpp

- Fixes a typo in the Firmware Tests preventing them from loading the firmware correctly.

Fixing a typo in the Firmware Tests.

---

docs/standards.md
include/k4a/k4a.h
src/csharp/SDK/Image.cs
src/image/image.c
tests/UnitTests/allocator_ut/allocator.cpp

- Modified k4a_image_create to allow "0" as a valid stride. When zero is specified, k4a_image_create infers the minimum necessary stride appropriate for the image format.

Enabled implicit stride in k4a_image_create

---

CMakeLists.txt

- Removes variables for CMake to set RPATH during install
I used the command `readelf -d libk4a.so | grep RUNPATH` to check RUNPATH in both the built binary and the installed binary. The built binary had a RUNPATH of `0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN:]` the installed binary had nothing.

RUNPATH only should be set during build

---

examples/undistort/main.cpp

- Simple fix of a helper in undistort to take camera type instead of just depth

Helper fix in undistort example

---

src/calibration/calibration.c

- Switching locale from process based to thread based and setting the locale based on the calibration raw data.

Set expected Locale for cJSON and calibration blob

---

tools/k4arecorder/main.cpp
tools/k4arecorder/recorder.cpp
tools/k4arecorder/recorder.h

- Allows user to enter 2-200,000us for exposure, this is in addition to continuing to allow -11 to 1 for the existing MFC implementation.
- Allows user to specify gain

Allows recorder to set exposure based on desired exposure setting.

---

include/k4ainternal/matroska_common.h
src/record/internal/matroska_write.cpp
src/record/sdk/record.cpp
tests/RecordTests/UnitTest/CMakeLists.txt
tests/RecordTests/UnitTest/playback_ut.cpp
tests/RecordTests/UnitTest/record_ut.cpp
tests/RecordTests/UnitTest/sample_recordings.cpp
tests/RecordTests/UnitTest/test_helpers.cpp

- Allow BGRA format captures in recording
- If the write queue is more than 2 seconds behind, print a warning about slow disk speed.

Allow recording BGRA color, and add warning for slow disk speeds

---

tools/k4aviewer/k4arecordingdockcontrol.cpp

- Sets the color conversion to BGRA so that colorized point cloud is usable on recordings.
-
-
Tested on a variety of recordings formats: MJPG, NV12, YUY2

Add set_color_conversion for recording playback

---

src/csharp/SDK/LargeArrayPool.cs
src/usbcommand/usbcommand.c

Fixed thread safety issue in LargePoolArray.cs. Garbage collector can be called on another thread after the x.IsAlive test and before buffer is assigned. This can lead to a null pointer exception as x.Target will be null after the garbage collector has freed it. 
(Refer to https://stackoverflow.com/questions/1687045/thread-safety-of-weakreference for more info.)
Add a test to see if buffer is null before using it.
Manually tested in application where issue was occurring. Confirmed fixed in that application.

Fix for issue #754. 

---

azure-pipelines.yml

The call is hanging on builds and the default is 2 hours. The confirmation only takes seconds

Lowering test task "Check OpenGL version" timeout to 5min

---

azure-pipelines.yml
tests/multidevice/multidevice.cpp

- Nano doesn't like to 30FPS devices running at the same time. So we limit max speed to 15FPS

ARM64 builds should runs multi device tests

---

src/transformation/rgbz.c
tests/Transformation/transformation.cpp
tests/multidevice/multidevice.cpp

- Added NEON implementation of rgbz.c
- Only supposed to work on aarch64.  Arm 32bit is excluded intentionally.
- Using [sse2neon](https://github.com/DLTcollab/sse2neon) could be faster to implement but that couldn't leverage the `vst3` instruction that NEON has
- Ran `transformation_ut` on Jetson TX2 (Aarch64) without actual device

add NEON support where SSE is supported

---

src/color/mfcamerareader.cpp
tools/k4arecorder/recorder.cpp

- Removed code to set auto gain - that is not supported
- Added debug info

K4aRecorder updated to not set gain to auto 

---

examples/green_screen/CMakeLists.txt
examples/opencv_compatibility/CMakeLists.txt
examples/opencv_compatibility/README.md

- Fix OpenCV version that written in the documenta of example program.
Azure Kinect Sensor SDK v1.4.0 and later has been tested with OpenCV 4.1.1.
- Remove the settings of include directory for OpenCV from CMakeLists.
It is not necessary because settings of include directory for OpenCV is done with OpenCV_LIBS.
It is redundant.

Minor fix about OpenCV

---

CHANGELOG.md
src/color/uvc_camerareader.cpp

- Drops image that fails to be decoded, which happens on PC's that are heavily loaded and can't always read image from sensor fast enough
Manual Testing will be done on Ubuntu with 3 camera's starting and stopping at random intervals. Expectation is that we will see warnings of dropped frames but no errors. 
NOTE: K4AViewer converts YUY and NV12 to bgra format for displaying purposes which are not being addressed. So those formats in that tool will still fail.

Dropping failed conversions from MJPEG

---

azure-pipelines.yml

We are currently using over 30 machines in parallel. This will reduce
our usage down to 15 machines by staggering the master and develop
builds as well as removing some build flavors we don't really care
about.

Reduce usage of build pools

---

azure-pipelines.yml

We are currently using over 30 machines in parallel. This will reduce
our usage down to 15 machines by staggering the master and develop
builds as well as removing some build flavors we don't really care
about.
* Update azure-pipelines.yml
Co-authored-by: wes-b <wesbarc@microsoft.com>
* Update azure-pipelines.yml
Co-authored-by: wes-b <wesbarc@microsoft.com>
Co-authored-by: wes-b <wesbarc@microsoft.com>

Reduce usage of build pools (#1222)
