microsoft/Azure-Kinect-Sensor-SDK

src/transformation/CMakeLists.txt
src/transformation/rgbz.c

- Enable SSE for depth to xyz code

Remove Windows only sse

---

tests/ColorTests/FunctionalTest/color_ft.cpp

- Recover exposure value and mode to default after colorExposureTest
- Change EXPECT_EQ to warning message.
- Recover exposure value and mode to default after colorExposureTest
- Change EXPECT_EQ to warning message.
Run color functional test (color_ft)

Fix functional test failure.

---

README.md

- Added MR Dev program link to the README.md 
-
-
This is a non-code change.

Added MR Dev Program link to the README.md

---

src/sdk/CMakeLists.txt

- Added k4a.hpp to the cmake install target
I built the SDK installer and confirmed the files are in the appropriate output paths.

Added k4a.hpp to output

---

CHANGELOG.md
CMakeLists.txt
include/k4a/k4a.hpp
tools/k4aviewer/k4arecordingdockcontrol.cpp
tools/k4aviewer/k4avideowindow.h

- Updated changelog.mg based on commits
- Rename C++ function

Update changelog.md for 1.1.x release

---

src/tewrapper/tewrapper.c

- Ensure the worker thread loop to acquire the worker lock before the process frame function in main thread acquires the worker lock to avoid dead lock
- Run K4aviewer.exe with long-haul
- Run an example of stress c++ wrapper to create transform handle in a loop with a device on a NUC PC to reproduce the original issue and then test the dead lock fix indeed fixed it with running 1000+ iterations without issue

Ensure the worker thread loop to acquire the worker lock first

---

docs/releasing.md

- Minor updates to match the package outputs

Updated paths in releasing.md

---

README.md
docs/building.md
docs/usage.md

- Added some more documentation for first time users

Clarify some getting started steps

---

CONTRIBUTING.md

- Adds who completes  pull requests to CONTRIBUTING.md
- Adds when pull requests are completed to CONTRIBUTING.md

Include merge timing in CONTRIBUTING.md

---

README.md

Adds nuget badge to readme

---

README.md

Added v1.1.0 link to README.md

---

src/usbcommand/usbstreaming.c
tests/throughput/throughput_perf.cpp

- Added Command line option
- Fixed non-error being reported: "ERROR LibUSB transfer status of 00000000 unexpected" Where status of 0 means success.

Throughput subordinate delay off master usec

---

doxygen/Doxyfile.in

- Update Doxyfile to generate a tag file as output

Enable Doxygen to generate a tag file

---

README.md
docs/usage.md

- Adds documentation for installing Linux Debian packages

Adds linux installation docs to usage.md

---

README.md

added Q&A section

---

docs/depthengine.md

- Linux is now supported, so updated that
- Removed links to old download info
- "proprietary" was misspelled

Removed old links, updated Linux info, spelling

---

scripts/bootstrap-ubuntu.sh

Added cmake to bootstrap-ubuntu.sh

---

.gitmodules

- Changed the GitHub submodule name

updating the LibUvc Submodule

---

src/csharp/Microsoft.Azure.Kinect.Sensor/Calibration.cs
src/csharp/Microsoft.Azure.Kinect.Sensor/Device.cs
src/csharp/Microsoft.Azure.Kinect.Sensor/Native/NativeReferenceAttributes.cs
src/csharp/Microsoft.Azure.Kinect.Sensor/NativeMethods.cs
src/csharp/Microsoft.Azure.Kinect.Sensor/Transformation.cs

- Tweaking the native DLL Imports to work on x86 projects

Tweaking the native DLL Imports to work on x86 projects

---

tests/executables/executables_ft.cpp

Fix test cases hanging

---

src/csharp/AzureKinectSensorSDK.editorconfig
src/csharp/Examples/WPF/App.xaml
src/csharp/Examples/WPF/App.xaml.cs
src/csharp/Examples/WPF/MainWindow.xaml
src/csharp/Examples/WPF/MainWindow.xaml.cs
src/csharp/Examples/WPF/Microsoft.Azure.Kinect.Sensor.Examples.WPFViewer.csproj
src/csharp/Examples/WPF/Properties/AssemblyInfo.cs
src/csharp/Examples/WinForms/Microsoft.Azure.Kinect.Sensor.Examples.WinForms.csproj
src/csharp/Examples/WinForms/Properties/AssemblyInfo.cs
src/csharp/Extensions/WPF/Microsoft.Azure.Kinect.Sensor.WPF.csproj
src/csharp/Extensions/WPF/Properties/AssemblyInfo.cs
src/csharp/Extensions/WinForms/Microsoft.Azure.Kinect.Sensor.WinForms.csproj
src/csharp/Extensions/WinForms/Properties/AssemblyInfo.cs
src/csharp/K4a.sln
src/csharp/SDK/BGRA.cs
src/csharp/SDK/Capture.cs
src/csharp/SDK/Microsoft.Azure.Kinect.Sensor.csproj
src/csharp/Tests/FunctionalTests/Microsoft.Azure.Kinect.Sensor.FunctionalTests.csproj
src/csharp/Tests/StubGenerator.UnitTests/Microsoft.Azure.Kinect.Sensor.Test.StubGenerator.UnitTests.csproj
src/csharp/Tests/StubGenerator/CallCount.cs
src/csharp/Tests/StubGenerator/CodeString.cs
src/csharp/Tests/StubGenerator/Microsoft.Azure.Kinect.Sensor.Test.StubGenerator.csproj
src/csharp/VersionInfo.cs

- Make sure that all project pull in an AssemblyInfo file.
- Adding a VersionInfo file to create a common version across the C# assemblies.
- Adding an editor config to standardize on the style we want VS to apply.

C# Asembly Info standardization

---

tools/k4aviewer/k4aimugraph.cpp
tools/k4aviewer/k4apointcloudshaders.h
tools/k4aviewer/k4arecordingdockcontrol.cpp
tools/k4aviewer/k4arecordingdockcontrol.h
tools/k4aviewer/k4aviewer.cpp

- Fix IMU graph label being delayed #504 
- Fix point cloud fragment shader deprecated usage #419
- Fix playback of PASSIVE_IR recordings #424 
- Add better error checking for failed window creation #453

Various K4A Viewer fixes

---

docs/usage.md

Adding 1.1.1 link to GitHub documentation

publishing link to 1.1.1

---

src/csharp/Examples/WPF/MainWindow.xaml.cs
src/csharp/Examples/WinForms/Form1.cs
src/csharp/SDK/AzureKinectMemoryCast.cs
src/csharp/SDK/AzureKinectMemoryManager.cs
src/csharp/SDK/Capture.cs
src/csharp/SDK/ColorControlCommand.cs
src/csharp/SDK/ColorControlMode.cs
src/csharp/SDK/ColorResolution.cs
src/csharp/SDK/DepthMode.cs
src/csharp/SDK/DeviceConfiguration.cs
src/csharp/SDK/FPS.cs
src/csharp/SDK/FirmwareBuild.cs
src/csharp/SDK/FirmwareSignature.cs
src/csharp/SDK/Hardwareversion.cs
src/csharp/SDK/Image.cs
src/csharp/SDK/ImageFormat.cs
src/csharp/SDK/ImuSample.cs
src/csharp/SDK/LargeArrayPool.cs
src/csharp/SDK/Short3.cs
src/csharp/SDK/Transformation.cs
src/csharp/SDK/WiredSyncMode.cs
src/csharp/Tests/FunctionalTests/Calibration.cs
src/csharp/Tests/UnitTests/DeviceFunctionTests.cs

Documented:
- All classes except Calibration

Updated documentation

---

src/csharp/SDK/Calibration.cs
src/csharp/SDK/CalibrationDeviceType.cs
src/csharp/SDK/CalibrationModelType.cs
src/csharp/SDK/CameraCalibration.cs
src/csharp/SDK/Extrinsics.cs
src/csharp/SDK/Intrinsics.cs
src/csharp/SDK/Native/NativeMethods.cs
src/csharp/SDK/Transformation.cs
src/csharp/Tests/FunctionalTests/Calibration.cs
src/csharp/Tests/UnitTests/DeviceFunctionTests.cs

- Moved calibration types outside of class scoped name

Renamed calibration types

---

CMakeLists.txt
src/csharp/Examples/WPF/MainWindow.xaml.cs
src/csharp/SDK/Calibration.cs
src/csharp/SDK/CalibrationDeviceType.cs
src/csharp/SDK/CalibrationModelType.cs
src/csharp/SDK/CameraCalibration.cs
src/csharp/SDK/Extrinsics.cs
src/csharp/SDK/Intrinsics.cs
src/csharp/SDK/Transformation.cs
src/csharp/Tests/FunctionalTests/Calibration.cs
src/csharp/Tests/UnitTests/DeviceFunctionTests.cs

- Completed documentation of calibration types.
- Enabled doxygen processing of c#

Added documentation for C# calibration types

---

src/csharp/SDK/Calibration.cs
src/csharp/SDK/CalibrationDeviceType.cs
src/csharp/SDK/CalibrationModelType.cs
src/csharp/SDK/CameraCalibration.cs
src/csharp/SDK/Extrinsics.cs
src/csharp/SDK/Intrinsics.cs
src/csharp/SDK/Microsoft.Azure.Kinect.Sensor.csproj
src/csharp/SDK/Properties/AssemblyInfo.cs

- Fixing a few straggling style issues.

More csharp

---

src/csharp/SDK/Native/NativeMethods.cs

- NativeMethods.cs style rules

Cleaned up NativeMethods.cs

---

cmake/k4aCompilerFlags.cmake
include/k4a/k4a.hpp
include/k4ainternal/global.h
src/record/internal/matroska_read.cpp
tests/UnitTests/depthmcu_ut/depthmcu_ut.cpp
tools/k4aviewer/k4apointcloudwindow.cpp

- Ignore some new warnings added in Clang 8
- Fix warnings from Clang 8 / GCC 9
- Updated ImGui to v1.72b to fix some warnings
Added comments inline about specific warning fixes.

Fix warnings on clang 8 / GCC 9

---

CMakeLists.txt
azure-pipelines.yml
docs/usage.md

- Adding 1.2.0 MSI, 
- Changing SDK version to 1.3, and
- Using the non-alpha Nuget Package for develop

Publishing 1.2.0

---

examples/green_screen/README.md

- There wasn't enough detail in the README, and it was a bit out-of-date. I added hopefully enough info for people to actually use this.

Update green screen readme

---

tools/k4aviewer/k4apointcloudvisualizer.cpp

- Fix the point cloud colorization image stride

Fix the point cloud colorization image stride

---

azure-pipelines.yml
examples/CMakeLists.txt
examples/green_screen/README.md

- Copy DLL's to bin folder so path updates are not required.
- Updated readme.md to reflect changes.

OpenCV does not need to be in users PATH

---

examples/green_screen/main.cpp

- Broke config function into default shared settings, and then a master and subordinate function.

Cleaned up code and comment around shared settings for multi sync

---

src/csharp/Examples/WinForms/Form1.cs

#683
- Change the way to generate the depth image from Bitmap.SetPixel to generate byte array and change it
I tested the changes running the device localy:

Performance improvement of Winforms' example

---

examples/transformation/main.cpp
examples/transformation/transformation_helpers.cpp
examples/transformation/transformation_helpers.h

- Provide code sample to demonstrate how to use transformation API (depth to color) on downscaled color image

Provide code sample to show how to use transformation on downscaled color image

---

azure-pipelines.yml

This change updates the NuGet package downloaded by our build systems

Using dynamically linked DepthEngine for tests.

---

CHANGELOG.md

Updated Chanr Log file with the latest 1.3.0 release notes.

Updated change Log with new release 1.3.0

---

include/k4arecord/record.hpp
src/record/sdk/CMakeLists.txt

- Add C++ wrapper for recording API.
Simple usage is as follows.
```cpp
// Include Header
#include <k4a/k4a.hpp>
#include <k4arecord/record.hpp>
// Open Device and Start Cameras
k4a::device device = k4a::device::open(device_index);
k4a_device_configuration_t device_configuration = K4A_DEVICE_CONFIG_INIT_DISABLE_ALL;
device_configuration.color_format             = K4A_IMAGE_FORMAT_COLOR_BGRA32;
device_configuration.color_resolution         = K4A_COLOR_RESOLUTION_720P;
device_configuration.depth_mode               = K4A_DEPTH_MODE_NFOV_UNBINNED;
device_configuration.synchronized_images_only = true;
device.start_cameras(&device_configuration);
// Create Record
k4a::record record = k4a::record::create("record.mkv", device, device_configuration);
// Write Header
record.write_header(); …
```

Add C++ wrapper for recording API

---

tests/ColorTests/FunctionalTest/color_ft.cpp

- Expanded tests to validate image exposure settings

expanded exposure tests to include checking image exposure

---

CHANGELOG.md
CMakeLists.txt
azure-pipelines.yml
docs/building.md
docs/releasing.md
docs/usage.md

- Bump binary version to 1.4.0
- Added 1.4 section to changelog.md
- moved Nuget to use newly release package

Develop branch is now version 1.4.0

---

azure-pipelines.yml
examples/green_screen/MultiDeviceCapturer.h
tests/ColorTests/FunctionalTest/color_ft.cpp
tests/multidevice/multidevice.cpp

This updates our automation to test the pending firmware in the 1.4.0 alpha package
Fixes #448, #529, #700, #784 
- TODO's removed from tests to work around firmware issues
- New multi sync tests added

Use new firmware 1.6.104075014

---

azure-pipelines.yml
examples/green_screen/CMakeLists.txt
examples/opencv_compatibility/CMakeLists.txt
scripts/install-opencv.ps1

- Change to link OpenCV that installed in the system even on Windows.
- Update OpenCV for CI environment.

Fix link OpenCV in case of Windows

---

src/transformation/rgbz.c

Fixing wrong error message

---

CONTRIBUTING.md

Added the description of the new feature request process.

Added the new process for new feature request

---

src/capturesync/capturesync.c
src/sdk/k4a.c
tests/UnitTests/utcommon/inc/utcommon.h
tests/multidevice/multidevice.cpp
tests/throughput/throughput_perf.cpp
tools/k4aviewer/k4adevicedockcontrol.cpp

- Better error messages around multi device delay settings being wrong
- K4aViewer now has a button to refresh the color controls if they change via firmware state change.
- A random number generating function
- Code uses random number generating common function

Minor Fixes Error Messages, K4aViewer Button, Multi Device Tests

---

CHANGELOG.md
src/transformation/intrinsic_transformation.c

Typo in transformation logic

---

src/transformation/intrinsic_transformation.c

- Updates warning to only fire 1 time per session instead of many
Manually tested to confirm change.

Reducing Rational 6KT error message rate

---

tests/multidevice/multidevice.cpp

Restore Parallel sensor start test

---

src/depth_mcu/depth_mcu.c

- Increased the device index sanity check to 100

Allow more than 10 devices to be connected

---

src/color/mfcamerareader.cpp

- This wait loop has been moved such that it is only called when Flush() has succeeded and we know the function was called.

Moving wait loop to only happen when Flush() succeeds

---

azure-pipelines.yml

This switches our internal builds to use the new firmware; 1.6.107078014.

Upgrading firmware used in the lab to 1.6.107078014

---

azure-pipelines.yml
scripts/RunTestList.py
src/usbcommand/usbcommand.c
tests/multidevice/multidevice.cpp

- Added command line options to set the FPS and delays

Adding command line parameters to multi_sync_validation test

---

tests/multidevice/multidevice.cpp

- This is fixed in Firmware 1.6.108079014.bin

Enabling depth only multi device test

---

src/csharp/SDK/Calibration.cs
src/csharp/SDK/Native/NativeMethods.cs
src/csharp/SDK/Transformation.cs
src/csharp/SDK/TransformationInterpolationType.cs

- This pull request will add thease missing functions to C# wrapper.
- Microsoft.Azure.Kinect.Sensor.DepthImageToColorCameraCustom()
This function wrapped k4a_transformation_depth_image_to_color_camera_custom().
- Microsoft.Azure.Kinect.Sensor.Calibration.TransformColor2DToDepth2d()
This function wrapped k4a_calibration_color_2d_to_depth_2d().

Add missing functions to C# wrapper

---

src/depth/depth.c

- Upgrades the warning for FW versions below 1.6.108079014

Updating the min FW version to 1.6.108079014

---

azure-pipelines.yml

- Attempt to test both DISPLAY :0 and DISPLAY :1

new script

---

azure-pipelines.yml

Firmware fixes for when device crashes and is unresponsive - LIBUSB reports error reading BOS descriptor.

Firmware changed

---

azure-pipelines.yml

Switching away from the ADO UI

Night builds managed by Azure-Pipelines.yml

---

scripts/install-opencv.ps1

Not sure why the script is currently failing there is not a single message from it.

Hardening OpenCV install script

---

scripts/install-opencv.ps1

Copying enhanced retry script to master to increase success rate of automation.

[CherryPick] opencv script hardening

---

azure-pipelines.yml

Moving use of stable firmware into master branch to ensure old firmware will not break the testing lab.

[CherryPick] Firmware upgraded to 1.6.110079014.bin (#1173)

---

azure-pipelines.yml

Getting Master to build nightly

Build master nightly

---

azure-pipelines.yml

cherry pick 4d4b82625a72debf97a8f27ce3cb7b1b3887e41a

[CherryPick] Build master nightly
